require 'stringio'
require 'time'  # for Time#httpdate
require 'rack/deflater'
require 'rack/mock'
require 'zlib'

describe Rack::Deflater do
  def build_response(status, body, accept_encoding, headers = {})
    body = [body]  if body.respond_to? :to_str
    app = lambda { |env| [status, {}, body] }
    request = Rack::MockRequest.env_for("", headers.merge("HTTP_ACCEPT_ENCODING" => accept_encoding))
    response = Rack::Deflater.new(app).call(request)

    return response
  end

  def inflate(buf)
    inflater = Zlib::Inflate.new(-Zlib::MAX_WBITS)
    inflater.inflate(buf) << inflater.finish
  end

  should "be able to deflate bodies that respond to each" do
    body = Object.new
    class << body; def each; yield("foo"); yield("bar"); end; end

    response = build_response(200, body, "deflate")

    response[0].should.equal(200)
    response[1].should.equal({
      "Content-Encoding" => "deflate",
      "Vary" => "Accept-Encoding"
    })
    buf = ''
    response[2].each { |part| buf << part }
    inflate(buf).should.equal("foobar")
  end

  should "flush deflated chunks to the client as they become ready" do
    body = Object.new
    class << body; def each; yield("foo"); yield("bar"); end; end

    response = build_response(200, body, "deflate")

    response[0].should.equal(200)
    response[1].should.equal({
      "Content-Encoding" => "deflate",
      "Vary" => "Accept-Encoding"
    })
    buf = []
    inflater = Zlib::Inflate.new(-Zlib::MAX_WBITS)
    response[2].each { |part| buf << inflater.inflate(part) }
    buf << inflater.finish
    buf.delete_if { |part| part.empty? }
    buf.should.equal(%w(foo bar))
  end

  # TODO: This is really just a special case of the above...
  should "be able to deflate String bodies" do
    response = build_response(200, "Hello world!", "deflate")

    response[0].should.equal(200)
    response[1].should.equal({
      "Content-Encoding" => "deflate",
      "Vary" => "Accept-Encoding"
    })
    buf = ''
    response[2].each { |part| buf << part }
    inflate(buf).should.equal("Hello world!")
  end

  should "be able to gzip bodies that respond to each" do
    body = Object.new
    class << body; def each; yield("foo"); yield("bar"); end; end

    response = build_response(200, body, "gzip")

    response[0].should.equal(200)
    response[1].should.equal({
      "Content-Encoding" => "gzip",
      "Vary" => "Accept-Encoding",
    })

    buf = ''
    response[2].each { |part| buf << part }
    io = StringIO.new(buf)
    gz = Zlib::GzipReader.new(io)
    gz.read.should.equal("foobar")
    gz.close
  end

  should "flush gzipped chunks to the client as they become ready" do
    body = Object.new
    class << body; def each; yield("foo"); yield("bar"); end; end

    response = build_response(200, body, "gzip")

    response[0].should.equal(200)
    response[1].should.equal({
      "Content-Encoding" => "gzip",
      "Vary" => "Accept-Encoding"
    })
    buf = []
    inflater = Zlib::Inflate.new(Zlib::MAX_WBITS + 32)
    response[2].each { |part| buf << inflater.inflate(part) }
    buf << inflater.finish
    buf.delete_if { |part| part.empty? }
    buf.should.equal(%w(foo bar))
  end

  should "be able to fallback to no deflation" do
    response = build_response(200, "Hello world!", "superzip")

    response[0].should.equal(200)
    response[1].should.equal({ "Vary" => "Accept-Encoding" })
    response[2].should.equal(["Hello world!"])
  end

  should "be able to skip when there is no response entity body" do
    response = build_response(304, [], "gzip")

    response[0].should.equal(304)
    response[1].should.equal({})
    response[2].should.equal([])
  end

  should "handle the lack of an acceptable encoding" do
    response1 = build_response(200, "Hello world!", "identity;q=0", "PATH_INFO" => "/")
    response1[0].should.equal(406)
    response1[1].should.equal({"Content-Type" => "text/plain", "Content-Length" => "71"})
    response1[2].should.equal(["An acceptable encoding for the requested resource / could not be found."])

    response2 = build_response(200, "Hello world!", "identity;q=0", "SCRIPT_NAME" => "/foo", "PATH_INFO" => "/bar")
    response2[0].should.equal(406)
    response2[1].should.equal({"Content-Type" => "text/plain", "Content-Length" => "78"})
    response2[2].should.equal(["An acceptable encoding for the requested resource /foo/bar could not be found."])
  end

  should "handle gzip response with Last-Modified header" do
    last_modified = Time.now.httpdate

    app = lambda { |env| [200, { "Last-Modified" => last_modified }, ["Hello World!"]] }
    request = Rack::MockRequest.env_for("", "HTTP_ACCEPT_ENCODING" => "gzip")
    response = Rack::Deflater.new(app).call(request)

    response[0].should.equal(200)
    response[1].should.equal({
      "Content-Encoding" => "gzip",
      "Vary" => "Accept-Encoding",
      "Last-Modified" => last_modified
    })

    buf = ''
    response[2].each { |part| buf << part }
    io = StringIO.new(buf)
    gz = Zlib::GzipReader.new(io)
    gz.read.should.equal("Hello World!")
    gz.close
  end

  should "do nothing when no-transform Cache-Control directive present" do
    app = lambda { |env| [200, {'Cache-Control' => 'no-transform'}, ['Hello World!']] }
    request = Rack::MockRequest.env_for("", "HTTP_ACCEPT_ENCODING" => "gzip")
    response = Rack::Deflater.new(app).call(request)

    response[0].should.equal(200)
    response[1].should.not.include "Content-Encoding"
    response[2].join.should.equal("Hello World!")
  end

  should "check Content-Type is suitable for deflate" do
    content_types = [
      'application/andrew-inset',
      'application/atom+xml',
      'application/atomcat+xml',
      'application/atomsvc+xml',
      'application/ccxml+xml',
      'application/cu-seeme',
      'application/davmount+xml',
      'application/dsptype',
      'application/ecmascript',
      'application/font-tdpfr',
      'application/hta',
      'application/hyperstudio',
      'application/java-archive',
      'application/java-serialized-object',
      'application/java-vm',
      'application/json',
      'application/mac-binhex40',
      'application/marc',
      'application/mathematica',
      'application/mathml+xml',
      'application/mbox',
      'application/mediaservercontrol+xml',
      'application/mp4',
      'application/msaccess',
      'application/msword',
      'application/mxf',
      'application/octet-stream',
      'application/oda',
      'application/ogg',
      'application/pdf',
      'application/pgp-keys',
      'application/pgp-signature',
      'application/pics-rules',
      'application/pkcs10',
      'application/pkcs7-mime',
      'application/pkcs7-signature',
      'application/pkix-pkipath',
      'application/pkixcmp',
      'application/postscript',
      'application/prs.cww',
      'application/rar',
      'application/rdf+xml',
      'application/reginfo+xml',
      'application/relax-ng-compact-syntax',
      'application/resource-lists+xml',
      'application/rls-services+xml',
      'application/rsd+xml',
      'application/rss+xml',
      'application/sbml+xml',
      'application/scvp-cv-request',
      'application/scvp-cv-response',
      'application/scvp-vp-request',
      'application/scvp-vp-response',
      'application/set-payment-initiation',
      'application/set-registration-initiation',
      'application/shf+xml',
      'application/smil',
      'application/sparql-query',
      'application/sparql-results+xml',
      'application/srgs',
      'application/srgs+xml',
      'application/ssml+xml',
      'application/vnd.3gpp.pic-bw-large',
      'application/vnd.3gpp.pic-bw-small',
      'application/vnd.3gpp.pic-bw-var',
      'application/vnd.3gpp2.tcap',
      'application/vnd.3m.post-it-notes',
      'application/vnd.accpac.simply.imp',
      'application/vnd.acucobol',
      'application/vnd.acucorp',
      'application/vnd.adobe.xdp+xml',
      'application/vnd.adobe.xfdf',
      'application/vnd.amiga.ami',
      'application/vnd.anser-web-certificate-issue-initiation',
      'application/vnd.anser-web-funds-transfer-initiation',
      'application/vnd.antix.game-component',
      'application/vnd.apple.installer+xml',
      'application/vnd.audiograph',
      'application/vnd.blueice.multipass',
      'application/vnd.bmi',
      'application/vnd.businessobjects',
      'application/vnd.chemdraw+xml',
      'application/vnd.cinderella',
      'application/vnd.claymore',
      'application/vnd.clonk.c4group',
      'application/vnd.commonspace',
      'application/vnd.contact.cmsg',
      'application/vnd.cosmocaller',
      'application/vnd.crick.clicker',
      'application/vnd.crick.clicker.keyboard',
      'application/vnd.crick.clicker.palette',
      'application/vnd.crick.clicker.template',
      'application/vnd.crick.clicker.wordbank',
      'application/vnd.criticaltools.wbs+xml',
      'application/vnd.ctc-posml',
      'application/vnd.cups-ppd',
      'application/vnd.curl',
      'application/vnd.data-vision.rdz',
      'application/vnd.denovo.fcselayout-link',
      'application/vnd.dna',
      'application/vnd.dolby.mlp',
      'application/vnd.dpgraph',
      'application/vnd.dreamfactory',
      'application/vnd.ecowin.chart',
      'application/vnd.enliven',
      'application/vnd.epson.esf',
      'application/vnd.epson.msf',
      'application/vnd.epson.quickanime',
      'application/vnd.epson.salt',
      'application/vnd.epson.ssf',
      'application/vnd.eszigno3+xml',
      'application/vnd.ezpix-album',
      'application/vnd.ezpix-package',
      'application/vnd.fdf',
      'application/vnd.flographit',
      'application/vnd.fluxtime.clip',
      'application/vnd.frogans.fnc',
      'application/vnd.frogans.ltf',
      'application/vnd.fsc.weblaunch',
      'application/vnd.fujitsu.oasys',
      'application/vnd.fujitsu.oasys2',
      'application/vnd.fujitsu.oasys3',
      'application/vnd.fujitsu.oasysgp',
      'application/vnd.fujitsu.oasysprs',
      'application/vnd.fujixerox.ddd',
      'application/vnd.fujixerox.docuworks',
      'application/vnd.fujixerox.docuworks.binder',
      'application/vnd.fuzzysheet',
      'application/vnd.genomatix.tuxedo',
      'application/vnd.google-earth.kml+xml',
      'application/vnd.google-earth.kmz',
      'application/vnd.grafeq',
      'application/vnd.groove-account',
      'application/vnd.groove-help',
      'application/vnd.groove-identity-message',
      'application/vnd.groove-injector',
      'application/vnd.groove-tool-message',
      'application/vnd.groove-tool-template',
      'application/vnd.groove-vcard',
      'application/vnd.handheld-entertainment+xml',
      'application/vnd.hbci',
      'application/vnd.hhe.lesson-player',
      'application/vnd.hp-hpgl',
      'application/vnd.hp-hpid',
      'application/vnd.hp-hps',
      'application/vnd.hp-jlyt',
      'application/vnd.hp-pcl',
      'application/vnd.hp-pclxl',
      'application/vnd.hzn-3d-crossword',
      'application/vnd.ibm.minipay',
      'application/vnd.ibm.modcap',
      'application/vnd.ibm.rights-management',
      'application/vnd.ibm.secure-container',
      'application/vnd.igloader',
      'application/vnd.immervision-ivp',
      'application/vnd.immervision-ivu',
      'application/vnd.intercon.formnet',
      'application/vnd.intu.qbo',
      'application/vnd.intu.qfx',
      'application/vnd.ipunplugged.rcprofile',
      'application/vnd.irepository.package+xml',
      'application/vnd.is-xpr',
      'application/vnd.jam',
      'application/vnd.jcp.javame.midlet-rms',
      'application/vnd.jisp',
      'application/vnd.joost.joda-archive',
      'application/vnd.kahootz',
      'application/vnd.kde.karbon',
      'application/vnd.kde.kformula',
      'application/vnd.kde.kivio',
      'application/vnd.kde.kontour',
      'application/vnd.kenameaapp',
      'application/vnd.kidspiration',
      'application/vnd.kinar',
      'application/vnd.llamagraphics.life-balance.desktop',
      'application/vnd.llamagraphics.life-balance.exchange+xml',
      'application/vnd.lotus-1-2-3',
      'application/vnd.lotus-approach',
      'application/vnd.lotus-freelance',
      'application/vnd.lotus-notes',
      'application/vnd.lotus-organizer',
      'application/vnd.lotus-screencam',
      'application/vnd.lotus-wordpro',
      'application/vnd.macports.portpkg',
      'application/vnd.mcd',
      'application/vnd.medcalcdata',
      'application/vnd.mediastation.cdkey',
      'application/vnd.mfer',
      'application/vnd.mfmp',
      'application/vnd.micrografx.flo',
      'application/vnd.micrografx.igx',
      'application/vnd.mobius.daf',
      'application/vnd.mobius.dis',
      'application/vnd.mobius.mbk',
      'application/vnd.mobius.mqy',
      'application/vnd.mobius.msl',
      'application/vnd.mobius.plc',
      'application/vnd.mobius.txf',
      'application/vnd.mophun.application',
      'application/vnd.mozilla.xul+xml',
      'application/vnd.ms-artgalry',
      'application/vnd.ms-cab-compressed',
      'application/vnd.ms-excel',
      'application/vnd.ms-fontobject',
      'application/vnd.ms-ims',
      'application/vnd.ms-lrm',
      'application/vnd.ms-pki.seccat',
      'application/vnd.ms-pki.stl',
      'application/vnd.ms-powerpoint',
      'application/vnd.ms-project',
      'application/vnd.ms-works',
      'application/vnd.ms-wpl',
      'application/vnd.ms-xpsdocument',
      'application/vnd.mseq',
      'application/vnd.musician',
      'application/vnd.muvee.style',
      'application/vnd.neurolanguage.nlu',
      'application/vnd.noblenet-directory',
      'application/vnd.noblenet-sealer',
      'application/vnd.noblenet-web',
      'application/vnd.nokia.n-gage.data',
      'application/vnd.nokia.n-gage.symbian.install',
      'application/vnd.nokia.radio-preset',
      'application/vnd.nokia.radio-presets',
      'application/vnd.novadigm.edm',
      'application/vnd.novadigm.edx',
      'application/vnd.novadigm.ext',
      'application/vnd.oasis.opendocument.chart',
      'application/vnd.oasis.opendocument.chart-template',
      'application/vnd.oasis.opendocument.database',
      'application/vnd.oasis.opendocument.formula',
      'application/vnd.oasis.opendocument.formula-template',
      'application/vnd.oasis.opendocument.graphics',
      'application/vnd.oasis.opendocument.graphics-template',
      'application/vnd.oasis.opendocument.image',
      'application/vnd.oasis.opendocument.image-template',
      'application/vnd.oasis.opendocument.presentation',
      'application/vnd.oasis.opendocument.presentation-template',
      'application/vnd.oasis.opendocument.spreadsheet',
      'application/vnd.oasis.opendocument.spreadsheet-template',
      'application/vnd.oasis.opendocument.text',
      'application/vnd.oasis.opendocument.text-master',
      'application/vnd.oasis.opendocument.text-template',
      'application/vnd.oasis.opendocument.text-web',
      'application/vnd.olpc-sugar',
      'application/vnd.oma.dd2+xml',
      'application/vnd.openofficeorg.extension',
      'application/vnd.osgi.dp',
      'application/vnd.palm',
      'application/vnd.pg.format',
      'application/vnd.pg.osasli',
      'application/vnd.picsel',
      'application/vnd.pocketlearn',
      'application/vnd.powerbuilder6',
      'application/vnd.previewsystems.box',
      'application/vnd.proteus.magazine',
      'application/vnd.publishare-delta-tree',
      'application/vnd.pvi.ptid1',
      'application/vnd.quark.quarkxpress',
      'application/vnd.recordare.musicxml',
      'application/vnd.rim.cod',
      'application/vnd.seemail',
      'application/vnd.sema',
      'application/vnd.semd',
      'application/vnd.semf',
      'application/vnd.shana.informed.formdata',
      'application/vnd.shana.informed.formtemplate',
      'application/vnd.shana.informed.interchange',
      'application/vnd.shana.informed.package',
      'application/vnd.simtech-mindmapper',
      'application/vnd.smaf',
      'application/vnd.solent.sdkm+xml',
      'application/vnd.spotfire.dxp',
      'application/vnd.spotfire.sfs',
      'application/vnd.stardivision.calc',
      'application/vnd.stardivision.draw',
      'application/vnd.stardivision.impress',
      'application/vnd.stardivision.math',
      'application/vnd.stardivision.writer',
      'application/vnd.stardivision.writer-global',
      'application/vnd.sun.xml.calc',
      'application/vnd.sun.xml.calc.template',
      'application/vnd.sun.xml.draw',
      'application/vnd.sun.xml.draw.template',
      'application/vnd.sun.xml.impress',
      'application/vnd.sun.xml.impress.template',
      'application/vnd.sun.xml.math',
      'application/vnd.sun.xml.writer',
      'application/vnd.sun.xml.writer.global',
      'application/vnd.sun.xml.writer.template',
      'application/vnd.sus-calendar',
      'application/vnd.svd',
      'application/vnd.symbian.install',
      'application/vnd.syncml+xml',
      'application/vnd.syncml.dm+wbxml',
      'application/vnd.syncml.dm+xml',
      'application/vnd.tao.intent-module-archive',
      'application/vnd.tmobile-livetv',
      'application/vnd.trid.tpt',
      'application/vnd.triscape.mxs',
      'application/vnd.trueapp',
      'application/vnd.ufdl',
      'application/vnd.uiq.theme',
      'application/vnd.umajin',
      'application/vnd.unity',
      'application/vnd.uoml+xml',
      'application/vnd.vcx',
      'application/vnd.visio',
      'application/vnd.visionary',
      'application/vnd.vsf',
      'application/vnd.wap.wbxml',
      'application/vnd.wap.wmlc',
      'application/vnd.wap.wmlscriptc',
      'application/vnd.webturbo',
      'application/vnd.wqd',
      'application/vnd.wt.stf',
      'application/vnd.xara',
      'application/vnd.xfdl',
      'application/vnd.yamaha.hv-dic',
      'application/vnd.yamaha.hv-script',
      'application/vnd.yamaha.hv-voice',
      'application/vnd.yamaha.smaf-audio',
      'application/vnd.yamaha.smaf-phrase',
      'application/vnd.yellowriver-custom-menu',
      'application/vnd.zzazz.deck+xml',
      'application/voicexml+xml',
      'application/winhlp',
      'application/wordperfect',
      'application/wordperfect5.1',
      'application/wsdl+xml',
      'application/wspolicy+xml',
      'application/x-123',
      'application/x-abiword',
      'application/x-ace-compressed',
      'application/x-apple-diskimage',
      'application/x-bcpio',
      'application/x-bittorrent',
      'application/x-bzip',
      'application/x-bzip2',
      'application/x-cdf',
      'application/x-cdlink',
      'application/x-chat',
      'application/x-chess-pgn',
      'application/x-cpio',
      'application/x-debian-package',
      'application/x-director',
      'application/x-dms',
      'application/x-doom',
      'application/x-dvi',
      'application/x-flac',
      'application/x-font',
      'application/x-freemind',
      'application/x-futuresplash',
      'application/x-gnumeric',
      'application/x-go-sgf',
      'application/x-graphing-calculator',
      'application/x-gtar',
      'application/x-hdf',
      'application/x-ica',
      'application/x-internet-signup',
      'application/x-iphone',
      'application/x-iso9660-image',
      'application/x-java-jnlp-file',
      'application/x-javascript',
      'application/x-jmol',
      'application/x-kchart',
      'application/x-killustrator',
      'application/x-koan',
      'application/x-kpresenter',
      'application/x-kspread',
      'application/x-kword',
      'application/x-latex',
      'application/x-lha',
      'application/x-lzh',
      'application/x-lzx',
      'application/x-maker',
      'application/x-mif',
      'application/x-ms-wmd',
      'application/x-ms-wmz',
      'application/x-msbinder',
      'application/x-mscardfile',
      'application/x-msclip',
      'application/x-msdos-program',
      'application/x-msi',
      'application/x-msmediaview',
      'application/x-msmetafile',
      'application/x-msmoney',
      'application/x-mspublisher',
      'application/x-msschedule',
      'application/x-msterminal',
      'application/x-mswrite',
      'application/x-netcdf',
      'application/x-ns-proxy-autoconfig',
      'application/x-nwc',
      'application/x-object',
      'application/x-oz-application',
      'application/x-pkcs12',
      'application/x-pkcs7-certificates',
      'application/x-pkcs7-certreqresp',
      'application/x-pkcs7-crl',
      'application/x-python-code',
      'application/x-quicktimeplayer',
      'application/x-redhat-package-manager',
      'application/x-shar',
      'application/x-shockwave-flash',
      'application/x-stuffit',
      'application/x-stuffitx',
      'application/x-sv4cpio',
      'application/x-sv4crc',
      'application/x-tar',
      'application/x-tex-gf',
      'application/x-tex-pk',
      'application/x-texinfo',
      'application/x-trash',
      'application/x-troff',
      'application/x-troff-man',
      'application/x-troff-me',
      'application/x-troff-ms',
      'application/x-ustar',
      'application/x-wais-source',
      'application/x-wingz',
      'application/x-x509-ca-cert',
      'application/x-xcf',
      'application/x-xfig',
      'application/x-xpinstall',
      'application/xenc+xml',
      'application/xhtml+xml',
      'application/xml',
      'application/xml-dtd',
      'application/xop+xml',
      'application/xslt+xml',
      'application/xspf+xml',
      'application/xv+xml',
      'application/zip',
      'audio/basic',
      'audio/midi',
      'audio/mp4',
      'audio/mp4a-latm',
      'audio/mpeg',
      'audio/prs.sid',
      'audio/vnd.digital-winds',
      'audio/vnd.lucent.voice',
      'audio/vnd.nuera.ecelp4800',
      'audio/vnd.nuera.ecelp7470',
      'audio/vnd.nuera.ecelp9600',
      'audio/x-aiff',
      'audio/x-gsm',
      'audio/x-mpegurl',
      'audio/x-ms-wax',
      'audio/x-ms-wma',
      'audio/x-pn-realaudio',
      'audio/x-pn-realaudio-plugin',
      'audio/x-realaudio',
      'audio/x-scpls',
      'audio/x-sd2',
      'audio/x-wav',
      'chemical/x-alchemy',
      'chemical/x-cache',
      'chemical/x-cache-csf',
      'chemical/x-cactvs-binary',
      'chemical/x-cdx',
      'chemical/x-cerius',
      'chemical/x-chem3d',
      'chemical/x-chemdraw',
      'chemical/x-cif',
      'chemical/x-cmdf',
      'chemical/x-cml',
      'chemical/x-compass',
      'chemical/x-crossfire',
      'chemical/x-csml',
      'chemical/x-ctx',
      'chemical/x-cxf',
      'chemical/x-embl-dl-nucleotide',
      'chemical/x-galactic-spc',
      'chemical/x-gamess-input',
      'chemical/x-gaussian-checkpoint',
      'chemical/x-gaussian-cube',
      'chemical/x-gaussian-input',
      'chemical/x-gaussian-log',
      'chemical/x-gcg8-sequence',
      'chemical/x-genbank',
      'chemical/x-hin',
      'chemical/x-isostar',
      'chemical/x-jcamp-dx',
      'chemical/x-kinemage',
      'chemical/x-macmolecule',
      'chemical/x-macromodel-input',
      'chemical/x-mdl-molfile',
      'chemical/x-mdl-rdfile',
      'chemical/x-mdl-rxnfile',
      'chemical/x-mdl-sdfile',
      'chemical/x-mdl-tgf',
      'chemical/x-mmcif',
      'chemical/x-mol2',
      'chemical/x-molconn-Z',
      'chemical/x-mopac-graph',
      'chemical/x-mopac-input',
      'chemical/x-mopac-out',
      'chemical/x-mopac-vib',
      'chemical/x-ncbi-asn1-ascii',
      'chemical/x-ncbi-asn1-binary',
      'chemical/x-ncbi-asn1-spec',
      'chemical/x-pdb',
      'chemical/x-rosdal',
      'chemical/x-swissprot',
      'chemical/x-vamas-iso14976',
      'chemical/x-vmd',
      'chemical/x-xtel',
      'chemical/x-xyz',
      'image/cgm',
      'image/g3fax',
      'image/gif',
      'image/ief',
      'image/jp2',
      'image/jpeg',
      'image/pcx',
      'image/pict',
      'image/png',
      'image/prs.btif',
      'image/svg+xml',
      'image/tiff',
      'image/vnd.djvu',
      'image/vnd.dwg',
      'image/vnd.dxf',
      'image/vnd.fastbidsheet',
      'image/vnd.fpx',
      'image/vnd.fst',
      'image/vnd.fujixerox.edmics-mmr',
      'image/vnd.fujixerox.edmics-rlc',
      'image/vnd.ms-modi',
      'image/vnd.net-fpx',
      'image/vnd.wap.wbmp',
      'image/vnd.xiff',
      'image/x-cmu-raster',
      'image/x-cmx',
      'image/x-coreldraw',
      'image/x-coreldrawpattern',
      'image/x-coreldrawtemplate',
      'image/x-corelphotopaint',
      'image/x-icon',
      'image/x-jg',
      'image/x-jng',
      'image/x-macpaint',
      'image/x-ms-bmp',
      'image/x-photoshop',
      'image/x-pict',
      'image/x-portable-anymap',
      'image/x-portable-bitmap',
      'image/x-portable-graymap',
      'image/x-portable-pixmap',
      'image/x-quicktime',
      'image/x-rgb',
      'image/x-xbitmap',
      'image/x-xpixmap',
      'image/x-xwindowdump',
      'message/rfc822',
      'model/iges',
      'model/mesh',
      'model/vnd.dwf',
      'model/vnd.gdl',
      'model/vnd.gtw',
      'model/vnd.mts',
      'model/vnd.vtu',
      'text/calendar',
      'text/comma-separated-values',
      'text/css',
      'text/h323',
      'text/html',
      'text/iuls',
      'text/mathml',
      'text/plain',
      'text/prs.lines.tag',
      'text/richtext',
      'text/rtf',
      'text/scriptlet',
      'text/sgml',
      'text/tab-separated-values',
      'text/texmacs',
      'text/uri-list',
      'text/vnd.fly',
      'text/vnd.fmi.flexstor',
      'text/vnd.in3d.3dml',
      'text/vnd.in3d.spot',
      'text/vnd.sun.j2me.app-descriptor',
      'text/vnd.wap.wml',
      'text/vnd.wap.wmlscript',
      'text/x-asm',
      'text/x-bibtex',
      'text/x-c',
      'text/x-c++hdr',
      'text/x-c++src',
      'text/x-chdr',
      'text/x-csh',
      'text/x-csrc',
      'text/x-fortran',
      'text/x-haskell',
      'text/x-java',
      'text/x-literate-haskell',
      'text/x-moc',
      'text/x-pascal',
      'text/x-pcs-gcd',
      'text/x-perl',
      'text/x-psp',
      'text/x-python',
      'text/x-setext',
      'text/x-sh',
      'text/x-tcl',
      'text/x-tex',
      'text/x-uuencode',
      'text/x-vcalendar',
      'text/x-vcard',
      'video/3gpp',
      'video/3gpp2',
      'video/dl',
      'video/dv',
      'video/fli',
      'video/gl',
      'video/h261',
      'video/h263',
      'video/h264',
      'video/jpeg',
      'video/jpm',
      'video/mj2',
      'video/mp4',
      'video/mpeg',
      'video/quicktime',
      'video/vnd.fvt',
      'video/vnd.mpegurl',
      'video/vnd.vivo',
      'video/x-flv',
      'video/x-la-asf',
      'video/x-mng',
      'video/x-ms-asf',
      'video/x-ms-wm',
      'video/x-ms-wmv',
      'video/x-ms-wmx',
      'video/x-ms-wvx',
      'video/x-msvideo',
      'video/x-sgi-movie',
      'x-conference/x-cooltalk',
      'x-world/x-vrml',
    ]

    content_type_deflate_expection = {
      "text/x-pascal" => true,
      "text/vnd.in3d.spot" => true,
      "application/vnd.yamaha.smaf-audio" => false,
      "application/marc" => true,
      "application/vnd.acucobol" => false,
      "text/vnd.wap.wmlscript" => true,
      "image/x-rgb" => false,
      "image/gif" => false,
      "application/vnd.stardivision.impress" => false,
      "application/x-dms" => false,
      "application/oda" => true,
      "application/vnd.shana.informed.interchange" => false,
      "chemical/x-cxf" => true,
      "application/vnd.grafeq" => false,
      "application/vnd.kde.karbon" => false,
      "application/vnd.novadigm.edx" => false,
      "application/x-mswrite" => false,
      "image/vnd.ms-modi" => false,
      "application/x-kspread" => false,
      "application/x-chat" => false,
      "application/x-msmoney" => false,
      "chemical/x-pdb" => true,
      "application/x-tex-gf" => false,
      "application/x-pkcs7-certreqresp" => false,
      "application/vnd.sus-calendar" => false,
      "application/vnd.kinar" => false,
      "application/vnd.kenameaapp" => false,
      "application/vnd.oasis.opendocument.chart-template" => false,
      "application/rar" => false,
      "application/srgs" => true,
      "application/vnd.pocketlearn" => false,
      "application/vnd.mseq" => false,
      "video/x-flv" => false,
      "image/pcx" => false,
      "application/x-ms-wmz" => false,
      "application/vnd.vsf" => false,
      "application/vnd.previewsystems.box" => false,
      "application/vnd.trid.tpt" => false,
      "application/vnd.mcd" => false,
      "application/x-kpresenter" => false,
      "video/mp4" => false,
      "application/xop+xml" => true,
      "application/xml" => true,
      "application/set-registration-initiation" => true,
      "application/vnd.ms-excel" => false,
      "chemical/x-mdl-molfile" => true,
      "application/vnd.ms-wpl" => false,
      "application/vnd.kidspiration" => false,
      "application/x-msdos-program" => false,
      "video/x-sgi-movie" => false,
      "model/mesh" => true,
      "image/x-cmx" => false,
      "application/x-shockwave-flash" => false,
      "application/vnd.novadigm.ext" => false,
      "application/vnd.ms-ims" => false,
      "application/reginfo+xml" => true,
      "application/vnd.crick.clicker.palette" => false,
      "chemical/x-cdx" => true,
      "application/x-msschedule" => false,
      "application/vnd.stardivision.writer-global" => false,
      "application/x-hdf" => false,
      "application/vnd.cosmocaller" => false,
      "application/vnd.fujitsu.oasys" => false,
      "application/vnd.solent.sdkm+xml" => true,
      "image/x-portable-bitmap" => false,
      "application/vnd.macports.portpkg" => false,
      "application/x-debian-package" => false,
      "chemical/x-cerius" => true,
      "application/vnd.ctc-posml" => false,
      "video/vnd.fvt" => false,
      "chemical/x-galactic-spc" => true,
      "audio/mpeg" => false,
      "application/vnd.oasis.opendocument.text-template" => false,
      "application/mp4" => false,
      "application/andrew-inset" => true,
      "application/vnd.sun.xml.calc.template" => true,
      "application/vnd.oasis.opendocument.database" => false,
      "application/x-redhat-package-manager" => false,
      "application/vnd.micrografx.igx" => false,
      "application/voicexml+xml" => true,
      "application/x-freemind" => false,
      "video/x-ms-wmv" => false,
      "text/uri-list" => true,
      "application/vnd.lotus-approach" => false,
      "application/vnd.oasis.opendocument.image" => false,
      "application/vnd.mfmp" => false,
      "application/vnd.pg.format" => false,
      "application/vnd.kahootz" => false,
      "video/x-ms-wmx" => false,
      "application/vnd.svd" => false,
      "application/vnd.llamagraphics.life-balance.exchange+xml" => true,
      "application/vnd.amiga.ami" => false,
      "image/vnd.djvu" => false,
      "application/vnd.yamaha.hv-dic" => false,
      "application/vnd.ms-cab-compressed" => false,
      "application/vnd.dna" => false,
      "application/x-kword" => false,
      "text/vnd.sun.j2me.app-descriptor" => true,
      "application/relax-ng-compact-syntax" => true,
      "application/atomsvc+xml" => true,
      "application/vnd.ms-lrm" => false,
      "application/vnd.oasis.opendocument.spreadsheet-template" => false,
      "application/vnd.oasis.opendocument.presentation-template" => false,
      "video/3gpp" => false,
      "text/x-sh" => true,
      "chemical/x-ncbi-asn1-binary" => true,
      "audio/basic" => false,
      "application/x-stuffitx" => false,
      "application/vnd.irepository.package+xml" => true,
      "application/vnd.hp-hpid" => false,
      "application/x-msmediaview" => false,
      "application/vnd.recordare.musicxml" => true,
      "application/vnd.sun.xml.draw" => true,
      "text/x-literate-haskell" => true,
      "text/x-bibtex" => true,
      "application/vnd.ezpix-package" => false,
      "application/x-msbinder" => false,
      "text/x-fortran" => true,
      "text/vnd.in3d.3dml" => true,
      "image/x-coreldrawtemplate" => false,
      "chemical/x-mdl-rdfile" => true,
      "chemical/x-macromodel-input" => true,
      "application/vnd.intu.qbo" => false,
      "application/pgp-signature" => true,
      "application/vnd.proteus.magazine" => false,
      "application/scvp-vp-request" => true,
      "application/winhlp" => true,
      "image/svg+xml" => false,
      "application/java-vm" => false,
      "application/x-bzip" => false,
      "application/vnd.ms-xpsdocument" => false,
      "audio/x-ms-wax" => false,
      "application/x-chess-pgn" => false,
      "application/vnd.chemdraw+xml" => true,
      "application/x-pkcs7-certificates" => false,
      "application/x-gnumeric" => false,
      "application/vnd.jam" => false,
      "x-world/x-vrml" => true,
      "application/x-bzip2" => false,
      "application/vnd.enliven" => false,
      "application/vnd.3gpp.pic-bw-large" => false,
      "application/vnd.fsc.weblaunch" => false,
      "application/vnd.spotfire.sfs" => false,
      "chemical/x-mdl-sdfile" => true,
      "application/xml-dtd" => true,
      "application/vnd.3m.post-it-notes" => false,
      "application/vnd.hp-pcl" => false,
      "application/vnd.ibm.secure-container" => false,
      "model/vnd.gdl" => true,
      "application/vnd.groove-tool-message" => false,
      "application/vnd.lotus-freelance" => false,
      "video/x-ms-wm" => false,
      "text/x-csh" => true,
      "application/vnd.epson.salt" => false,
      "application/vnd.dolby.mlp" => false,
      "application/vnd.mobius.dis" => false,
      "application/vnd.sun.xml.writer.template" => true,
      "application/vnd.stardivision.calc" => false,
      "application/vnd.rim.cod" => false,
      "video/h261" => false,
      "application/x-troff-man" => false,
      "application/vnd.ms-project" => false,
      "application/x-oz-application" => false,
      "x-conference/x-cooltalk" => true,
      "image/x-jng" => false,
      "image/g3fax" => false,
      "application/x-x509-ca-cert" => false,
      "application/x-troff" => false,
      "application/vnd.symbian.install" => false,
      "application/msaccess" => true,
      "application/vnd.ipunplugged.rcprofile" => false,
      "video/h263" => false,
      "audio/vnd.nuera.ecelp4800" => false,
      "video/h264" => false,
      "chemical/x-ncbi-asn1-spec" => true,
      "application/vnd.dpgraph" => false,
      "application/ogg" => false,
      "application/vnd.lotus-screencam" => false,
      "image/vnd.fpx" => false,
      "application/smil" => true,
      "application/x-kchart" => false,
      "application/vnd.crick.clicker" => false,
      "text/x-uuencode" => true,
      "chemical/x-alchemy" => true,
      "application/x-go-sgf" => false,
      "application/vnd.groove-injector" => false,
      "application/font-tdpfr" => true,
      "application/vnd.antix.game-component" => false,
      "application/vnd.apple.installer+xml" => true,
      "model/vnd.vtu" => true,
      "application/vnd.blueice.multipass" => false,
      "text/x-chdr" => true,
      "audio/x-mpegurl" => false,
      "application/sbml+xml" => true,
      "application/vnd.contact.cmsg" => false,
      "image/pict" => false,
      "application/x-cdlink" => false,
      "application/vnd.tmobile-livetv" => false,
      "audio/x-realaudio" => false,
      "application/resource-lists+xml" => true,
      "application/vnd.kde.kontour" => false,
      "application/x-ns-proxy-autoconfig" => false,
      "application/vnd.hp-jlyt" => false,
      "application/vnd.oma.dd2+xml" => true,
      "application/vnd.jcp.javame.midlet-rms" => false,
      "application/x-maker" => false,
      "video/quicktime" => false,
      "text/texmacs" => true,
      "image/x-ms-bmp" => false,
      "application/vnd.fujixerox.docuworks.binder" => false,
      "application/vnd.unity" => false,
      "application/vnd.oasis.opendocument.formula-template" => false,
      "application/vnd.crick.clicker.wordbank" => false,
      "image/x-coreldrawpattern" => false,
      "chemical/x-xyz" => true,
      "chemical/x-mopac-vib" => true,
      "audio/mp4a-latm" => false,
      "application/vnd.clonk.c4group" => false,
      "application/vnd.anser-web-certificate-issue-initiation" => false,
      "application/x-ica" => false,
      "text/x-pcs-gcd" => true,
      "text/comma-separated-values" => true,
      "application/scvp-cv-response" => true,
      "application/vnd.nokia.n-gage.data" => false,
      "application/vnd.openofficeorg.extension" => false,
      "application/vnd.fujixerox.ddd" => false,
      "application/vnd.oasis.opendocument.text" => false,
      "application/x-stuffit" => false,
      "application/json" => true,
      "application/x-apple-diskimage" => false,
      "image/png" => false,
      "audio/vnd.digital-winds" => false,
      "application/x-xfig" => false,
      "application/x-mspublisher" => false,
      "application/vnd.frogans.ltf" => false,
      "application/vnd.sun.xml.math" => true,
      "application/vnd.sun.xml.writer" => true,
      "application/vnd.yamaha.hv-script" => false,
      "application/x-ustar" => false,
      "application/java-archive" => false,
      "application/vnd.sun.xml.impress.template" => true,
      "application/vnd.tao.intent-module-archive" => false,
      "application/vnd.yamaha.hv-voice" => false,
      "text/richtext" => true,
      "application/x-tar" => false,
      "application/vnd.ibm.rights-management" => false,
      "application/vnd.curl" => false,
      "application/vnd.immervision-ivp" => false,
      "application/vnd.oasis.opendocument.text-web" => false,
      "video/jpm" => false,
      "image/x-portable-anymap" => false,
      "application/x-wais-source" => false,
      "application/vnd.bmi" => false,
      "chemical/x-mopac-out" => true,
      "chemical/x-ncbi-asn1-ascii" => true,
      "chemical/x-crossfire" => true,
      "chemical/x-cactvs-binary" => true,
      "application/vnd.hp-hpgl" => false,
      "application/ecmascript" => true,
      "application/set-payment-initiation" => true,
      "text/x-psp" => true,
      "chemical/x-gaussian-cube" => true,
      "application/x-doom" => false,
      "text/x-c++hdr" => true,
      "application/vnd.3gpp.pic-bw-small" => false,
      "application/vnd.oasis.opendocument.graphics" => false,
      "application/vnd.acucorp" => false,
      "application/wordperfect5.1" => true,
      "application/vnd.nokia.n-gage.symbian.install" => false,
      "application/vnd.immervision-ivu" => false,
      "application/x-jmol" => false,
      "application/vnd.mobius.txf" => false,
      "chemical/x-gamess-input" => true,
      "application/rsd+xml" => true,
      "application/vnd.pvi.ptid1" => false,
      "application/vnd.ms-fontobject" => false,
      "text/x-vcard" => true,
      "image/cgm" => false,
      "chemical/x-swissprot" => true,
      "application/vnd.palm" => false,
      "application/vnd.intercon.formnet" => false,
      "application/vnd.picsel" => false,
      "application/x-java-jnlp-file" => false,
      "application/vnd.sun.xml.writer.global" => true,
      "application/vnd.ufdl" => false,
      "application/vnd.wap.wmlscriptc" => false,
      "image/prs.btif" => false,
      "application/vnd.lotus-organizer" => false,
      "application/x-font" => false,
      "image/vnd.fst" => false,
      "audio/x-pn-realaudio-plugin" => false,
      "application/vnd.ms-pki.stl" => false,
      "application/vnd.triscape.mxs" => false,
      "application/mediaservercontrol+xml" => true,
      "application/pkcs10" => true,
      "text/rtf" => true,
      "text/mathml" => true,
      "image/tiff" => false,
      "audio/x-sd2" => false,
      "application/vnd.is-xpr" => false,
      "application/pkcs7-signature" => true,
      "application/x-lha" => false,
      "application/x-xpinstall" => false,
      "application/vnd.eszigno3+xml" => true,
      "application/vnd.ecowin.chart" => false,
      "video/x-la-asf" => false,
      "application/postscript" => false,
      "application/x-gtar" => false,
      "application/vnd.ms-powerpoint" => false,
      "application/x-netcdf" => false,
      "application/vnd.oasis.opendocument.chart" => false,
      "application/x-python-code" => true,
      "application/davmount+xml" => true,
      "application/vnd.jisp" => false,
      "application/vnd.hbci" => false,
      "application/vnd.google-earth.kml+xml" => true,
      "application/ccxml+xml" => true,
      "application/vnd.groove-account" => false,
      "application/vnd.hzn-3d-crossword" => false,
      "image/x-quicktime" => false,
      "chemical/x-mdl-rxnfile" => true,
      "audio/x-scpls" => false,
      "video/dl" => false,
      "image/jpeg" => false,
      "chemical/x-kinemage" => true,
      "application/xspf+xml" => true,
      "application/vnd.commonspace" => false,
      "application/vnd.dreamfactory" => false,
      "application/vnd.groove-vcard" => false,
      "application/vnd.flographit" => false,
      "text/x-perl" => true,
      "chemical/x-rosdal" => true,
      "chemical/x-hin" => true,
      "chemical/x-gaussian-checkpoint" => true,
      "application/vnd.epson.msf" => false,
      "text/tab-separated-values" => true,
      "image/jp2" => false,
      "chemical/x-mol2" => true,
      "audio/vnd.nuera.ecelp7470" => false,
      "application/pkixcmp" => true,
      "application/vnd.ezpix-album" => false,
      "application/vnd.genomatix.tuxedo" => false,
      "chemical/x-ctx" => true,
      "application/vnd.yellowriver-custom-menu" => false,
      "application/vnd.fluxtime.clip" => false,
      "application/atom+xml" => true,
      "application/vnd.pg.osasli" => false,
      "application/vnd.smaf" => false,
      "application/vnd.mobius.msl" => false,
      "application/scvp-vp-response" => true,
      "image/vnd.fastbidsheet" => false,
      "application/vnd.oasis.opendocument.presentation" => false,
      "application/vnd.fdf" => false,
      "application/vnd.nokia.radio-presets" => false,
      "image/x-macpaint" => false,
      "application/hta" => true,
      "video/x-msvideo" => false,
      "image/vnd.dwg" => false,
      "audio/x-gsm" => false,
      "application/x-sv4crc" => false,
      "application/sparql-query" => true,
      "application/vnd.wap.wbxml" => true,
      "application/vnd.igloader" => false,
      "application/x-cdf" => false,
      "text/x-csrc" => true,
      "chemical/x-gaussian-log" => true,
      "application/vnd.stardivision.draw" => false,
      "application/vnd.noblenet-sealer" => false,
      "application/x-dvi" => false,
      "application/vnd.publishare-delta-tree" => false,
      "application/vnd.zzazz.deck+xml" => true,
      "image/x-photoshop" => false,
      "application/vnd.sun.xml.impress" => true,
      "application/vnd.3gpp2.tcap" => false,
      "application/vnd.osgi.dp" => false,
      "audio/vnd.nuera.ecelp9600" => false,
      "application/rss+xml" => true,
      "application/vnd.webturbo" => false,
      "application/pkcs7-mime" => true,
      "text/x-moc" => true,
      "chemical/x-mmcif" => true,
      "audio/x-wav" => false,
      "application/xhtml+xml" => true,
      "video/dv" => false,
      "audio/x-aiff" => false,
      "application/x-troff-me" => false,
      "application/pics-rules" => true,
      "application/vnd.simtech-mindmapper" => false,
      "application/mac-binhex40" => true,
      "audio/x-pn-realaudio" => false,
      "application/vnd.hp-pclxl" => false,
      "application/x-mif" => false,
      "application/vnd.adobe.xdp+xml" => true,
      "application/vnd.xfdl" => false,
      "video/mj2" => false,
      "chemical/x-embl-dl-nucleotide" => true,
      "chemical/x-cml" => true,
      "application/vnd.shana.informed.formtemplate" => false,
      "application/ssml+xml" => true,
      "text/x-setext" => true,
      "text/css" => true,
      "image/vnd.fujixerox.edmics-rlc" => false,
      "application/x-wingz" => false,
      "application/vnd.fujitsu.oasys2" => false,
      "application/vnd.ms-artgalry" => false,
      "application/wspolicy+xml" => true,
      "text/x-tex" => true,
      "text/x-java" => true,
      "text/calendar" => true,
      "image/vnd.fujixerox.edmics-mmr" => false,
      "application/vnd.sun.xml.calc" => true,
      "application/vnd.fujitsu.oasys3" => false,
      "application/vnd.umajin" => false,
      "application/hyperstudio" => true,
      "text/prs.lines.tag" => true,
      "application/vnd.groove-help" => false,
      "application/vnd.nokia.radio-preset" => false,
      "application/vnd.anser-web-funds-transfer-initiation" => false,
      "video/x-mng" => false,
      "text/plain" => true,
      "application/mbox" => true,
      "application/vnd.noblenet-directory" => false,
      "application/mathematica" => true,
      "text/scriptlet" => true,
      "chemical/x-mopac-graph" => true,
      "audio/vnd.lucent.voice" => false,
      "application/atomcat+xml" => true,
      "application/vnd.ibm.minipay" => false,
      "application/vnd.mobius.mbk" => false,
      "application/java-serialized-object" => false,
      "application/vnd.medcalcdata" => false,
      "application/x-pkcs7-crl" => false,
      "application/vnd.oasis.opendocument.formula" => false,
      "application/vnd.kde.kivio" => false,
      "application/vnd.syncml+xml" => true,
      "application/x-iso9660-image" => false,
      "image/x-portable-graymap" => false,
      "image/x-pict" => false,
      "chemical/x-chem3d" => true,
      "application/xslt+xml" => true,
      "application/vnd.xara" => false,
      "application/vnd.seemail" => false,
      "application/vnd.stardivision.writer" => false,
      "application/x-msi" => false,
      "application/x-pkcs12" => false,
      "application/vnd.criticaltools.wbs+xml" => true,
      "application/x-abiword" => false,
      "application/x-msclip" => false,
      "application/pgp-keys" => true,
      "application/vnd.neurolanguage.nlu" => false,
      "text/x-c++src" => true,
      "image/vnd.wap.wbmp" => false,
      "application/x-trash" => false,
      "application/vnd.3gpp.pic-bw-var" => false,
      "application/vnd.joost.joda-archive" => false,
      "application/vnd.quark.quarkxpress" => false,
      "application/pkix-pkipath" => true,
      "text/x-vcalendar" => true,
      "application/vnd.sun.xml.draw.template" => true,
      "application/vnd.cups-ppd" => false,
      "video/jpeg" => false,
      "text/x-python" => true,
      "text/vnd.wap.wml" => true,
      "application/x-troff-ms" => false,
      "application/x-tex-pk" => false,
      "application/vnd.frogans.fnc" => false,
      "application/vnd.fuzzysheet" => false,
      "application/wordperfect" => true,
      "application/vnd.vcx" => false,
      "application/vnd.visionary" => false,
      "application/sparql-results+xml" => true,
      "application/mxf" => true,
      "application/srgs+xml" => true,
      "video/gl" => false,
      "text/x-tcl" => true,
      "chemical/x-compass" => true,
      "application/vnd.groove-tool-template" => false,
      "application/vnd.sema" => false,
      "image/x-cmu-raster" => false,
      "chemical/x-mdl-tgf" => true,
      "application/vnd.llamagraphics.life-balance.desktop" => false,
      "application/vnd.olpc-sugar" => false,
      "application/vnd.fujitsu.oasysgp" => false,
      "application/vnd.crick.clicker.keyboard" => false,
      "application/vnd.epson.ssf" => false,
      "application/vnd.ms-works" => false,
      "text/vnd.fmi.flexstor" => true,
      "model/vnd.dwf" => true,
      "message/rfc822" => true,
      "chemical/x-isostar" => true,
      "chemical/x-csml" => true,
      "application/pdf" => false,
      "application/vnd.mobius.plc" => false,
      "application/prs.cww" => true,
      "application/vnd.semd" => false,
      "application/vnd.muvee.style" => false,
      "application/shf+xml" => true,
      "video/x-ms-wvx" => false,
      "application/vnd.accpac.simply.imp" => false,
      "application/vnd.semf" => false,
      "application/x-internet-signup" => false,
      "application/vnd.groove-identity-message" => false,
      "application/octet-stream" => false,
      "application/vnd.powerbuilder6" => false,
      "text/sgml" => true,
      "model/vnd.gtw" => true,
      "image/x-xpixmap" => false,
      "chemical/x-molconn-Z" => true,
      "image/x-corelphotopaint" => false,
      "image/vnd.xiff" => false,
      "chemical/x-mopac-input" => true,
      "application/vnd.epson.quickanime" => false,
      "application/vnd.claymore" => false,
      "application/x-futuresplash" => false,
      "application/vnd.wap.wmlc" => false,
      "text/vnd.fly" => true,
      "text/h323" => true,
      "image/ief" => false,
      "audio/midi" => false,
      "application/x-bcpio" => false,
      "application/vnd.oasis.opendocument.graphics-template" => false,
      "application/vnd.uiq.theme" => false,
      "application/vnd.shana.informed.formdata" => false,
      "application/vnd.data-vision.rdz" => false,
      "application/x-lzh" => false,
      "chemical/x-cache" => true,
      "application/xenc+xml" => true,
      "application/vnd.oasis.opendocument.spreadsheet" => false,
      "application/x-javascript" => true,
      "application/wsdl+xml" => true,
      "application/vnd.lotus-wordpro" => false,
      "application/x-123" => false,
      "chemical/x-xtel" => true,
      "audio/mp4" => false,
      "application/vnd.ibm.modcap" => false,
      "application/x-iphone" => false,
      "application/vnd.fujixerox.docuworks" => false,
      "application/vnd.google-earth.kmz" => false,
      "application/vnd.lotus-notes" => false,
      "application/vnd.denovo.fcselayout-link" => false,
      "application/vnd.handheld-entertainment+xml" => true,
      "application/vnd.syncml.dm+wbxml" => true,
      "application/x-msmetafile" => false,
      "application/vnd.mobius.mqy" => false,
      "video/vnd.vivo" => false,
      "image/x-coreldraw" => false,
      "chemical/x-cmdf" => true,
      "application/cu-seeme" => true,
      "application/x-cpio" => false,
      "application/x-mscardfile" => false,
      "application/vnd.adobe.xfdf" => false,
      "application/vnd.syncml.dm+xml" => true,
      "application/x-quicktimeplayer" => false,
      "application/vnd.wt.stf" => false,
      "model/iges" => true,
      "application/vnd.crick.clicker.template" => false,
      "text/x-asm" => true,
      "image/vnd.net-fpx" => false,
      "chemical/x-jcamp-dx" => true,
      "audio/x-ms-wma" => false,
      "application/vnd.intu.qfx" => false,
      "application/x-director" => false,
      "video/3gpp2" => false,
      "text/html" => true,
      "image/x-xwindowdump" => false,
      "application/x-ms-wmd" => false,
      "application/vnd.yamaha.smaf-phrase" => false,
      "image/x-jg" => false,
      "chemical/x-chemdraw" => true,
      "application/zip" => false,
      "application/x-object" => false,
      "application/vnd.fujitsu.oasysprs" => false,
      "application/x-koan" => false,
      "chemical/x-macmolecule" => true,
      "application/x-shar" => false,
      "application/vnd.musician" => false,
      "application/vnd.mobius.daf" => false,
      "image/x-xbitmap" => false,
      "chemical/x-vmd" => true,
      "application/dsptype" => true,
      "application/vnd.cinderella" => false,
      "application/rdf+xml" => true,
      "text/iuls" => true,
      "application/vnd.businessobjects" => false,
      "application/x-ace-compressed" => false,
      "application/vnd.hp-hps" => false,
      "application/vnd.epson.esf" => false,
      "application/x-xcf" => false,
      "application/x-sv4cpio" => false,
      "application/vnd.mfer" => false,
      "application/x-latex" => false,
      "application/x-texinfo" => false,
      "application/vnd.wqd" => false,
      "application/vnd.mediastation.cdkey" => false,
      "application/x-lzx" => false,
      "application/vnd.novadigm.edm" => false,
      "application/vnd.spotfire.dxp" => false,
      "application/vnd.kde.kformula" => false,
      "application/vnd.lotus-1-2-3" => false,
      "application/vnd.noblenet-web" => false,
      "application/scvp-cv-request" => true,
      "video/fli" => false,
      "application/vnd.hhe.lesson-player" => false,
      "application/vnd.shana.informed.package" => false,
      "text/x-c" => true,
      "chemical/x-gcg8-sequence" => true,
      "application/x-msterminal" => false,
      "application/vnd.mophun.application" => false,
      "application/vnd.oasis.opendocument.image-template" => false,
      "application/x-flac" => false,
      "chemical/x-cif" => true,
      "application/vnd.visio" => false,
      "application/x-nwc" => false,
      "application/msword" => true,
      "application/x-killustrator" => false,
      "video/x-ms-asf" => false,
      "video/vnd.mpegurl" => false,
      "video/mpeg" => false,
      "model/vnd.mts" => true,
      "image/x-portable-pixmap" => false,
      "image/vnd.dxf" => false,
      "chemical/x-cache-csf" => true,
      "application/xv+xml" => true,
      "application/vnd.trueapp" => false,
      "application/x-graphing-calculator" => false,
      "application/vnd.uoml+xml" => true,
      "application/vnd.micrografx.flo" => false,
      "text/x-haskell" => true,
      "image/x-icon" => false,
      "chemical/x-gaussian-input" => true,
      "application/vnd.stardivision.math" => false,
      "application/x-bittorrent" => false,
      "audio/prs.sid" => false,
      "application/vnd.oasis.opendocument.text-master" => false,
      "application/vnd.ms-pki.seccat" => false,
      "application/mathml+xml" => true,
      "chemical/x-vamas-iso14976" => true,
      "chemical/x-genbank" => true,
      "application/vnd.audiograph" => false,
      "application/rls-services+xml" => true,
      "application/vnd.mozilla.xul+xml" => true}
    content_type_check_result = {}
    app = lambda { |env| [status, {}, body] }
    deflater = Rack::Deflater.new(app)
    content_types.map { |mime|
      content_type_check_result[mime] = deflater.deflate_type?(mime)
    }
    content_type_check_result.should.equal(content_type_deflate_expection)
  end
end
