#!/usr/bin/env ruby
# frozen_string_literal: true

# -*- ruby -*-

$: << File.join(File.dirname(__FILE__), "..", "..", "lib")

require 'rack'
require '../testrequest'

Rack::Handler::CGI.run(Rack::Lint.new(TestRequest.new))
