AllCops:
  TargetRubyVersion: 2.2
  DisabledByDefault: true
  Exclude:
    - '**/vendor/**/*'

# Use Ruby >= 1.9 syntax for hashes. Prefer { a: :b } over { :a => :b }.
Style/HashSyntax:
  Enabled: true
