AllCops:
  TargetRubyVersion: 2.2
  DisabledByDefault: true
  Exclude:
    - '**/vendor/**/*'

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# Use Ruby >= 1.9 syntax for hashes. Prefer { a: :b } over { :a => :b }.
Style/HashSyntax:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/LeadingCommentSpace:
  Enabled: true
  Exclude:
    - 'test/builder/options.ru'
