module Rack
  # This module contains frozen singleton copies of all CGI variable names.
  module CGI_VARIABLE
    CONTENT_LENGTH = "CONTENT_LENGTH".freeze
    CONTENT_TYPE = "CONTENT_TYPE".freeze
    DOCUMENT_ROOT = "DOCUMENT_ROOT".freeze
    HTTP_ACCEPT = "HTTP_ACCEPT".freeze
    HTTP_ACCEPT_CHARSET = "HTTP_ACCEPT_CHARSET".freeze
    HTTP_ACCEPT_ENCODING = "HTTP_ACCEPT_ENCODING".freeze
    HTTP_ACCEPT_LANGUAGE = "HTTP_ACCEPT_LANGUAGE".freeze
    HTTP_CACHE_CONTROL = "HTTP_CACHE_CONTROL".freeze
    HTTP_CONNECTION = "HTTP_CONNECTION".freeze
    HTTP_CONTENT_LENGTH = "HTTP_CONTENT_LENGTH".freeze
    HTTP_CONTENT_TYPE = "HTTP_CONTENT_TYPE".freeze
    HTTP_COOKIE = "HTTP_COOKIE".freeze
    HTTP_HOST = "HTTP_HOST".freeze
    HTTP_IF_MODIFIED_SINCE = "HTTP_IF_MODIFIED_SINCE".freeze
    HTTP_IF_NONE_MATCH = "HTTP_IF_NONE_MATCH".freeze
    HTTP_KEEP_ALIVE = "HTTP_KEEP_ALIVE".freeze
    HTTP_METHOD_OVERRIDE_HEADER = "HTTP_X_HTTP_METHOD_OVERRIDE".freeze
    HTTP_PORT = "HTTP_PORT".freeze
    HTTP_RANGE = "HTTP_RANGE".freeze
    HTTP_REFERER = "HTTP_REFERER".freeze
    HTTP_USER_AGENT = "HTTP_USER_AGENT".freeze
    HTTP_VERSION = "HTTP_VERSION".freeze
    HTTP_X_FORWARDED_FOR = "HTTP_X_FORWARDED_FOR".freeze
    HTTP_X_FORWARDED_HOST = "HTTP_X_FORWARDED_HOST".freeze
    HTTP_X_FORWARDED_PROTO = "HTTP_X_FORWARDED_PROTO".freeze
    HTTP_X_REQUESTED_WITH = "HTTP_X_REQUESTED_WITH".freeze
    HTTPS = "HTTPS".freeze
    PATH_INFO = "PATH_INFO".freeze
    QUERY_STRING = "QUERY_STRING".freeze
    PHP_FCGI_CHILDREN = "PHP_FCGI_CHILDREN".freeze
    REMOTE_ADDR = "REMOTE_ADDR".freeze
    REMOTE_PORT = "REMOTE_PORT".freeze
    REMOTE_USER = "REMOTE_USER".freeze
    REQUEST_METHOD = "REQUEST_METHOD".freeze
    REQUEST_PATH = "REQUEST_PATH".freeze
    REQUEST_URI = "REQUEST_URI".freeze
    SCRIPT_NAME = "SCRIPT_NAME".freeze
    SERVER_ADDR = "SERVER_ADDR".freeze
    SERVER_ADMIN = "SERVER_ADMIN".freeze
    SERVER_NAME = "SERVER_NAME".freeze
    SERVER_PORT = "SERVER_PORT".freeze
    SERVER_PROTOCOL = "SERVER_PROTOCOL".freeze
    SERVER_SOFTWARE = "SERVER_SOFTWARE".freeze
  end
end
